// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/library": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/library" | "/settings";
  };
  "routes/matrix-layout.tsx": {
    id: "routes/matrix-layout";
    page: "/" | "/library" | "/settings";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/library.tsx": {
    id: "routes/library";
    page: "/library";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/matrix-layout": typeof import("./app/routes/matrix-layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/library": typeof import("./app/routes/library.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};