cmake_minimum_required(VERSION 3.22)
project(boxdroid_driver LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS OFF)
add_subdirectory(libadrenotools)
add_library(boxdroid_driver SHARED loader.cpp)
target_link_libraries(boxdroid_driver adrenotools log dl)
target_compile_options(boxdroid_driver PRIVATE -Wall -Wextra)
