#ifndef BOXDROID_M5_DIAGNOSTICS_H
#define BOXDROID_M5_DIAGNOSTICS_H

#include <stdint.h>

typedef enum BoxDroidM5Diagnostic {
    BOXDROID_M5_DIAG_REFRESH_CALLBACK,
    BOXDROID_M5_DIAG_GRAPHIC_HW_UPDATE,
    BOXDROID_M5_DIAG_PCRTC_START,
    BOXDROID_M5_DIAG_VGA_CRTC_WRITE,
    BOXDROID_M5_DIAG_PGRAPH_COLOR_DMA,
    BOXDROID_M5_DIAG_PGRAPH_SURFACE_FORMAT,
    BOXDROID_M5_DIAG_PGRAPH_SURFACE_PITCH,
    BOXDROID_M5_DIAG_PGRAPH_COLOR_OFFSET,
    BOXDROID_M5_DIAG_COLOR_BINDING,
    BOXDROID_M5_DIAG_FRAMEBUFFER_LOOKUP,
    BOXDROID_M5_DIAG_FRAMEBUFFER_HIT,
    BOXDROID_M5_DIAG_FRAMEBUFFER_MISS,
    BOXDROID_M5_DIAG_READBACK_BEGIN,
    BOXDROID_M5_DIAG_READBACK_COMPLETE,
    BOXDROID_M5_DIAG_DISPLAY_CALLBACK,
    BOXDROID_M5_DIAG_FRAME_PRESENT,
    BOXDROID_M5_DIAG_COUNT,
} BoxDroidM5Diagnostic;

void boxdroid_m5_diag_event(BoxDroidM5Diagnostic event,
                            uint64_t a, uint64_t b, uint64_t c,
                            uint64_t d, uint64_t e, uint64_t f);
void boxdroid_m5_diag_summary(void);

#endif
